import type { Metadata } from 'next'
import Link from 'next/link'
import { Breadcrumbs } from '@/components/Shell'
import { affiliate, site } from '@/lib/config'
import { JsonLd, breadcrumbJsonLd, canonical } from '@/lib/seo'

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: `The terms governing use of ${site.name}: informational use only, no warranty on modelled estimates, affiliate compensation disclosure and limitation of liability.`,
  alternates: { canonical: canonical('/terms/') },
}

const UPDATED = 'August 27, 2026'

export default function Terms() {
  const crumbs = [
    { name: 'Home', path: '/' },
    { name: 'Terms', path: '/terms/' },
  ]

  return (
    <article className="prose-body">
      <JsonLd data={breadcrumbJsonLd(crumbs)} />
      <Breadcrumbs items={crumbs} />

      <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl dark:text-white">
        Terms of Use
      </h1>
      <p className="mt-5 text-lg">
        These terms govern your use of {site.name} at {site.domain}. By using the site
        you accept them. If you do not accept them, do not use the site.
      </p>
      <p className="text-sm text-slate-500 dark:text-slate-500">
        Last updated: {UPDATED}
      </p>

      <h2>Informational purposes only</h2>
      <p>
        {site.name} publishes estimated car insurance costs and reference material about
        state coverage requirements. Everything on the site is provided for general
        information and comparison shopping. It is not an offer of insurance, not a
        quote, not a binding rate, and not a solicitation of an application.
      </p>
      <p>
        No relationship of any kind is created between you and us by your use of the
        site. Nothing on it is a promise that insurance is available to you, at any
        price, from any company.
      </p>

      <h2>Estimates and no warranty of accuracy</h2>
      <p>
        Every premium figure on this site is produced by a published arithmetic model
        applied to state-average base rates. The full model, its multipliers, its data
        sources and its known limitations are documented on the{' '}
        <Link href="/methodology/">methodology page</Link>. Read it before you rely on
        any number here.
      </p>
      <p>
        We make no warranty that these estimates are accurate, current or applicable to
        your circumstances. The model excludes factors that materially affect real
        pricing, including credit-based insurance scores, discounts, specific vehicle
        identification, ZIP-level rating and carrier tier placement. Base rates and
        statutory limits change; a static site lags those changes. Your actual premium
        will differ, in many cases substantially. Carrier index values are modelled
        relative positions used to order a shortlist and are not quoted prices.
      </p>
      <p>
        The site is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without
        warranties of any kind, express or implied, including implied warranties of
        merchantability, fitness for a particular purpose, accuracy, and
        non-infringement. We do not warrant that the site will be uninterrupted,
        error-free or free of harmful components.
      </p>

      <h2>Not an insurer, agent or broker</h2>
      <p>
        {site.name} is an independent comparison and information site. We are not an
        insurance company, an insurance agency, a producer, a broker or an adjuster. We
        are not licensed to transact insurance in any state, we do not underwrite risk,
        we do not bind coverage, and we do not handle claims.
      </p>
      <p>
        Nothing here is insurance, legal, tax or financial advice. Decisions about
        coverage types, limits, deductibles and carriers should be made with a licensed
        insurance professional in your state, and legal questions with a qualified
        lawyer. Statutory minimum limits shown on the site are our reading of published
        state requirements and may be out of date; verify them with your state Department
        of Insurance.
      </p>

      <h2>Advertising and affiliate compensation</h2>
      <p>
        This site is free to use and is funded by advertising and referral fees.{' '}
        {affiliate.disclosure}
      </p>
      <p>
        We may be paid when you click a partner link, request a quote, or buy a policy
        through one of our partners. Compensation may vary between partners. We also
        display advertising served by a third-party network; we do not control which
        advertisers appear, and their appearance here is not an endorsement. Carrier
        rankings and shortlists on this site are generated by the published model and are
        not sold, but you should treat any comparison site — including this one — as one
        input among several rather than as impartial advice.
      </p>

      <h2>Third-party links and services</h2>
      <p>
        The site links to insurers, quote providers, government agencies and data
        sources. Those sites are operated by others. We do not control them, we do not
        endorse their content, products, prices or terms, and we are not responsible for
        them. Your dealings with any third party, including any quote you request or
        policy you buy, are solely between you and that party, and are governed by their
        terms and privacy policy.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          Scrape, crawl or bulk-copy the site&apos;s content or data beyond ordinary
          browsing and normal search engine indexing.
        </li>
        <li>
          Republish the estimates, tables or datasets as if they were quoted rates, or
          present them without the accompanying statement that they are modelled
          estimates.
        </li>
        <li>
          Attempt to interfere with the site, circumvent its advertising, or introduce
          malicious code.
        </li>
        <li>Use the site for any unlawful purpose, or in breach of these terms.</li>
      </ul>

      <h2>Intellectual property</h2>
      <p>
        The site&apos;s text, layout, design, code and the compiled rate model are owned
        by {site.name} and are protected by copyright. You may read, print and share
        individual pages for personal, non-commercial use, and you may quote short
        excerpts with attribution and a link to the source page. Any other reproduction,
        redistribution or commercial use requires our written permission.
      </p>
      <p>
        Underlying source data carries its own licences, which are identified on the{' '}
        <Link href="/methodology/">methodology page</Link>; where a source requires
        attribution, that attribution is given there and must be preserved in any reuse.
        Insurance company names, logos and trademarks belong to their respective owners
        and are used on this site for identification only. Their use does not imply any
        affiliation with, sponsorship by or endorsement from those companies.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, {site.name}, its owners and its
        contributors will not be liable for any indirect, incidental, special,
        consequential, exemplary or punitive damages, or for any loss of profits,
        revenue, data or goodwill, arising out of or connected with your use of, or
        inability to use, the site — including any decision you make on the basis of an
        estimate published here, any difference between an estimate and a real premium,
        any gap in coverage, any denied claim, and any dealing with an advertiser or
        affiliate partner. This applies whether the claim is in contract, tort,
        negligence, strict liability or otherwise, and whether or not we were advised of
        the possibility of such damages.
      </p>
      <p>
        Where liability cannot lawfully be excluded, our total aggregate liability to you
        for all claims relating to the site is limited to one hundred United States
        dollars (US$100). Some jurisdictions do not allow the exclusion of certain
        warranties or the limitation of certain damages, so parts of this section may not
        apply to you.
      </p>

      <h2>Indemnity</h2>
      <p>
        You agree to indemnify and hold harmless {site.name} and its owners from any
        claim, demand, loss or expense, including reasonable legal fees, arising from
        your misuse of the site, your breach of these terms, or your violation of any law
        or the rights of a third party.
      </p>

      <h2>Availability</h2>
      <p>
        We may change, suspend or discontinue any part of the site, including any page,
        dataset or feature, at any time and without notice. We are under no obligation to
        keep any URL, figure or table available.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may revise these terms at any time. The revised version takes effect when it
        is posted here, and the date at the top of this page will change. Your continued
        use of the site after that point constitutes acceptance of the revised terms. If
        you do not agree to a change, stop using the site.
      </p>

      <h2>Governing law and severability</h2>
      <p>
        These terms are governed by the laws of the United States and of the state in
        which the site&apos;s operator is established, without regard to conflict of law
        rules. If any provision is held unenforceable, that provision will be limited or
        removed to the minimum extent necessary and the remaining provisions will stay in
        full force.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms:{' '}
        <a href={`mailto:${site.email}`}>{site.email}</a>.
      </p>
      <p>
        See also our <Link href="/privacy/">privacy policy</Link> and the{' '}
        <Link href="/methodology/">methodology</Link> behind every estimate on this site.
      </p>
    </article>
  )
}
